vich_uploader:
    db_driver: orm

    mappings:
        attachment:
            uri_prefix: '%kernel.project_dir%/public/gallery/images'
            upload_destination: '%kernel.project_dir%/public/gallery/images'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
