vich_uploader:
    db_driver: orm

    mappings:
        attachment:
            uri_prefix: '%kernel.project_dir%/public/folder/images'
            upload_destination: '%kernel.project_dir%/public/folder/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
